# -------- Data paths (TREC DL-2019) --------
queries_path: msmarco-test2020-queries.tsv.gz      # Gzipped TSV: qid<TAB>query
top100_path: msmarco-doctest2020-top100.gz         # Gzipped run: qid Q0 docid rank score
qrels_path: 2020qrels.txt                     # Plain-text qrels: qid Q0 docid rating
test_docs_path: msmarco-docs.tsv.gz                # Gzipped TREC collection (TSV)
docs_json_path: docs2020.json                     # JSON file with docid and content

# -------- FAISS index --------
index_path: faiss2020.index                             # Where to save / load the FAISS index

# -------- Model & evaluation parameters --------
model_name: intfloat/e5-small                       # Sentence-Transformer model
metrics:                                            # pytrec_eval metrics
  - ndcg_cut_10
  - recip_rank
  - map
alpha: 0.5
beta: 1
